config/routes.rb
Rails.application.routes.draw do
  root                 'static_pages#home'
  get '/help',     to: 'static_pages#help'
  get '/about',    to: 'static_pages#about'
  get '/contact',  to: 'static_pages#contact'
  get '/sign_up',  to: 'users#new'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the sample app!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private def user_params
    params.require(:user).permit(:name, :email, :password, 
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'RoR Tutorial Sample App'
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Gravatar return
  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="railstutorial.org">RoR tutorial</a>
  </small>
  <nav>
    <ul>
    <li><%= link_to "About", about_path%></li>
    <li><%= link_to "Contact", contact_path%></li>
    <li><a href="https://news.learnenough.com/"></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo"%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path%> </li>
        <li><%= link_to "help", help_path%> </li>
        <li><%= link_to "Log in", "#"%> </li>
      </ul>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title))%> </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer"%>
    <%= debug(params) if Rails.env.development?%>
  </div>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?%>
  <div id="error_explanation">
    <div class="alert alert-dangerous">
      There are <%= pluralize(@user.errors.count, "error")%>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg|%>
      <li><%= msg%></li>
    <%end%>
    </ul>
  </div>
<%end%>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>What's that all About?!</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>
<h1>We've made Contact!</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help a brotha out!</h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">

  <h1> Welcome home! </h1>

  <h2>This is our home page!</h2>

  <%= link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-primary"%>

  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maiores tempora rerum ducimus a  hic nesciunt aut fugit autem nulla facere tenetur beatae quis, reprehenderit perspiciatis  repellendus libero odio similique voluptate.</p>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                      "https://rubyonrails.org/" %>
<%# <%= image_tag("cat.jpg", alt: "kitty", width: "400") %> 

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<h1>Sign up here</h1>
<p>Join us!</p>
<div class="row">
  <div class="col-md-6 justify-content-center col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f|%>
      <%= render 'shared/error_messages'%>

      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control"%>

      <%= f.label :email%>
      <%= f.email_field :email, class: "form-control"%>

      <%= f.label :password%>
      <%= f.password_field :password, class: "form-control"%>

      <%= f.label :password_confirmation, "Confirm Password"%>
      <%= f.password_field :password_confirmation, class: "form-control"%>
      
      <%= f.submit "Create Account", class: "btn text-center btn-primary"%>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user%>
        <%= @user.name%>
      </h1>
    </section>
  </aside>
</div>